![](https://raw.githubusercontent.com/sambitmukherjee/handson-ml3-pytorch/main/chapter10/Figure_10-3.png)

**Source:** Aurelien Geron's book <a href="https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/" target="_blank">Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow</a>

In this notebook, we shall try to implement the above neurons using PyTorch.

If running this notebook in Colab, please ensure that your Hugging Face `HF_TOKEN` is added to your Colab secrets.

Alternatively, please login to Hugging Face by running the following cell.

In [1]:
# !huggingface-cli login

# IDENTITY

In [2]:
import torch
import torch.nn as nn
from huggingface_hub import PyTorchModelHubMixin

Let's create a column vector containing two values - `0` and `1`.

In [3]:
batch = torch.tensor([[0], [1]])
batch

tensor([[0],
        [1]])

In [4]:
class IDENTITY(nn.Module, PyTorchModelHubMixin):
    """
    A neuron that performs the IDENTITY logical computation.
    It is inspired by McCulloch & Pitts' 1943 paper 'A Logical Calculus of the Ideas Immanent in Nervous Activity'.
    It doesn't contain any parameters.
    It takes as input a single column vector of zeros and ones. It outputs a single column vector of zeros and ones.
    Its mechanism is outlined in Figure 10-3 of Aurelien Geron's book 'Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow'.
    Like all the other neurons in Figure 10-3, it is activated when at least two of its input connections are active.
    """

    def __init__(self):
        super().__init__()
        self.operation = "C = A"

    def forward(self, x):
        a = x
        inputs = torch.cat([a, a], dim=1)
        column_sum = torch.sum(inputs, dim=1, keepdim=True)
        output = (column_sum >= 2).long()
        return output

In [5]:
identity = IDENTITY()
identity

IDENTITY()

Forward pass:

In [6]:
identity(batch)

tensor([[0],
        [1]])

The IDENTITY operation works.

Let's push our model to the Hugging Face Hub.

In [7]:
# identity.push_to_hub("identity", commit_message="made a cosmetic update to the `forward` method")

# AND

Let's create two column vectors containing `0`s and `1`s.

In [8]:
batch = {'a': torch.tensor([[0], [0], [1], [1]]), 'b': torch.tensor([[0], [1], [0], [1]])}
batch

{'a': tensor([[0],
         [0],
         [1],
         [1]]),
 'b': tensor([[0],
         [1],
         [0],
         [1]])}

Our objective is to generate the following truth table using a single neuron.

| A | B | C |
| - | - | - |
| 0 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 1 | 1 | 1 |

In [9]:
class AND(nn.Module, PyTorchModelHubMixin):
    """
    A neuron that performs the AND logical computation.
    It is inspired by McCulloch & Pitts' 1943 paper 'A Logical Calculus of the Ideas Immanent in Nervous Activity'.
    It doesn't contain any parameters.
    It takes as input two column vectors of zeros and ones. It outputs a single column vector of zeros and ones.
    Its mechanism is outlined in Figure 10-3 of Aurelien Geron's book 'Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow'.
    Like all the other neurons in Figure 10-3, it is activated when at least two of its input connections are active.
    """

    def __init__(self):
        super().__init__()
        self.operation = "C = A AND B"

    def forward(self, x):
        a = x['a']
        b = x['b']
        inputs = torch.cat([a, b], axis=1)
        column_sum = torch.sum(inputs, dim=1, keepdim=True)
        output = (column_sum >= 2).long()
        return output

In [10]:
logical_and = AND()
logical_and

AND()

Forward pass:

In [11]:
logical_and(batch)

tensor([[0],
        [0],
        [0],
        [1]])

The AND operation works.

Let's push our model to the Hugging Face Hub.

In [12]:
# logical_and.push_to_hub("and", commit_message="pushing AND")

# OR

Our objective is to generate the following truth table using a single neuron.

| A | B | C |
| - | - | - |
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 1 |

In [13]:
class OR(nn.Module, PyTorchModelHubMixin):
    """
    A neuron that performs the OR logical computation.
    It is inspired by McCulloch & Pitts' 1943 paper 'A Logical Calculus of the Ideas Immanent in Nervous Activity'.
    It doesn't contain any parameters.
    It takes as input two column vectors of zeros and ones. It outputs a single column vector of zeros and ones.
    Its mechanism is outlined in Figure 10-3 of Aurelien Geron's book 'Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow'.
    Like all the other neurons in Figure 10-3, it is activated when at least two of its input connections are active.
    """

    def __init__(self):
        super().__init__()
        self.operation = "C = A OR B"

    def forward(self, x):
        a = x['a']
        b = x['b']
        inputs = torch.cat([a, a, b, b], axis=1)
        column_sum = torch.sum(inputs, dim=1, keepdim=True)
        output = (column_sum >= 2).long()
        return output

In [14]:
logical_or = OR()
logical_or

OR()

Forward pass:

In [15]:
logical_or(batch)

tensor([[0],
        [1],
        [1],
        [1]])

The OR operation works.

Let's push our model to the Hugging Face Hub.

In [16]:
# logical_or.push_to_hub("or", commit_message="pushing OR")

# A AND (NOT B)

Our objective is to generate the following truth table using a single neuron.

| A | B | C |
| - | - | - |
| 0 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 1 |
| 1 | 1 | 0 |

In [17]:
class A_AND_NOT_B(nn.Module, PyTorchModelHubMixin):
    """
    A neuron that performs the A AND (NOT B) logical computation.
    It is inspired by McCulloch & Pitts' 1943 paper 'A Logical Calculus of the Ideas Immanent in Nervous Activity'.
    It doesn't contain any parameters.
    It takes as input two column vectors of zeros and ones. It outputs a single column vector of zeros and ones.
    Its mechanism is outlined in Figure 10-3 of Aurelien Geron's book 'Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow'.
    Like all the other neurons in Figure 10-3, it is activated when at least two of its input connections are active.
    """

    def __init__(self):
        super().__init__()
        self.operation = "C = A AND (NOT B)"

    def forward(self, x):
        a = x['a']
        b = x['b']
        b = -1 * b
        inputs = torch.cat([a, a, b], axis=1)
        column_sum = torch.sum(inputs, dim=1, keepdim=True)
        output = (column_sum >= 2).long()
        return output

In [18]:
a_and_not_b = A_AND_NOT_B()
a_and_not_b

A_AND_NOT_B()

Forward pass:

In [19]:
a_and_not_b(batch)

tensor([[0],
        [0],
        [1],
        [0]])

The A AND (NOT B) operation works.

Let's push our model to the Hugging Face Hub.

In [20]:
# a_and_not_b.push_to_hub("a-and-not-b", commit_message="pushing A_AND_NOT_B")